    
#  Copyright (C) 2019 Alek Frohlich <alek.frohlich@gmail.com> 
#  & Gustavo Biage <gustavo.c.biage@gmail.com>.
 
#  This file is a part of Albi.
 
#  Albi is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
 
#  Albi is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
 
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

# Albi's BNF grammar

<start_of_prog> ::= ""
                  | <start_of_prog> <parameter> EOL
                  | <start_of_prog> <program> EOL

<parameter> ::= <statement>

<statement> ::= VAR ASSIGN NUM ';'

<program> ::= <program_def> <program_body> ';' 

<program_def> ::= PROG VAR ASSIGN

<program_body> ::= '{' <program_content_list> '}'

<program_content_list> ::= <specie> 
                         | <rate>
                         | <program_content_list> <specie> 
                         | <program_content_list> <rate>

<specie> ::= <statement>

<rate> ::= <rate_def> <rate_body>

<rate_def> ::= RATE '(' VAR ')' ':' 

<rate_body> ::= '{' <reagent_list> '}'

<reagent_list> ::= <product> 
                 | <reactant>
                 | <reagent_list> <product>
                 | <reagent_list> <reactant>

<product> ::= VAR ASSIGN VAR '+' NUM ';'

<reactant> ::= VAR ASSIGN VAR '-' NUM ';'